Footer
G-Gateway-React/ecommerce-mb pull request #11
Opened 2022-07-30 20:35 UTC by moath143

Please review the footer section code in footer branch

2022-08-14 10:38 UTC, Mossa-99 requested changes

2022-08-14 10:38 UTC, Mossa-99 commented on src/components/checkboxCatalog/CheckBoxCatalog.tsx
> +            }}
inline styles

2022-08-14 10:38 UTC, Mossa-99 commented on src/components/footer/Footer.tsx
> +            padding: "0",
inline styles

2022-08-14 10:38 UTC, Mossa-99 commented on src/components/footer/Footer.tsx
> +                textTransform: "uppercase",
Please use styled components

2022-08-14 10:38 UTC, Mossa-99 commented on src/pages/catalog/Catalog.tsx
> +            <ImagesShirts style={{ margin: "30px 0 10px 0" }}>
inline styles

2022-09-04 06:42 UTC, yasmeentayeh99 approved these changes

2022-09-04 07:11 UTC, merged