Login signup
G-Gateway-React/ecommerce-mb pull request #13
Opened 2022-07-31 17:16 UTC by moath143

Issue #12 
Login and Sign up pages are finished and @yasmeentayeh99  will complete the validation for the forms

2022-08-21 08:05 UTC, mossa-Sammer requested changes

2022-08-21 08:05 UTC, mossa-Sammer commented on src/components/input/Input.tsx
> +    <>
unneccssary fragment

2022-08-21 08:05 UTC, mossa-Sammer commented on src/components/input/Input.tsx
> +const Input: React.FC<InputProps> = (props) => {
Your are limiting the TextField API to only two props while you can use the interface provided by materail-ui for the text field

2022-08-21 08:05 UTC, mossa-Sammer commented on src/components/navbar/Navbar.tsx
> +//: React.FC<NavbarProps>
commented code

2022-08-21 08:05 UTC, mossa-Sammer commented on src/components/navbar/Navbar.tsx
> -    <Grid sx={{margin: 0, padding: '10px 0'}} container spacing={3}>
Please use styled components

2022-09-04 06:44 UTC, yasmeentayeh99 approved these changes

2022-09-04 07:11 UTC, merged