Edit Product Page
G-Gateway-React/ecommerce-mb pull request #18
Opened 2022-08-16 07:41 UTC by yasmeentayeh99

Create Product Page

2022-08-21 08:42 UTC, mossa-Sammer requested changes, later dismissed
The slider should follow the design
![image](https://user-images.githubusercontent.com/37276951/185782907-68426575-5f24-4d7e-8654-989a2f3c80af.png)

![image](https://user-images.githubusercontent.com/37276951/185782936-4ee45516-2b03-4368-97ff-be36ad052d00.png)

The color buttons should rounded and match the design

2022-08-21 08:42 UTC, mossa-Sammer commented on src/components/Acordinate/Acordinate.tsx
> +            {/*</Accordion>*/}
commented code

2022-08-21 08:42 UTC, mossa-Sammer commented on src/components/Swiper/Swiper.tsx
> +                            <Buttons background={'#9126f8'} ></Buttons>
You can use an array of colors and map through them instead of dublicating the components

2022-09-04 07:12 UTC, moath143 approved these changes

2022-09-04 07:32 UTC, merged